function flag=choose_euler(r,flag,a,b,c,num)

TOL=1.0e-12;

if flag==0 ...
   & (cos(a)*cos(b)*cos(c)-sin(a)*sin(c))-(r(1,1)) < TOL ...
   & (sin(a)*cos(b)*cos(c)+cos(a)*sin(c))-(r(1,2)) < TOL ...
   & (-cos(a)*cos(b)*sin(c)-sin(a)*cos(c))-(r(2,1)) < TOL ...
   & (-sin(a)*cos(b)*sin(c)+cos(a)*cos(c))-(r(2,2)) < TOL ...
   & (cos(a)*sin(b)) -(r(3,1)) < TOL
   flag=num;
end